### ISSUE TITLE
Error Building slicer/slicer-build docker image

### ISSUE THREAD

**Issue by MayeulChassagnard** [thewtex/SlicerDocker#16]
We can't build the docker image: `bash build.sh`

Here the error that I have:
![docker-slicer-build](https://cloud.githubusercontent.com/assets/20341270/19489645/0ef5e68a-953a-11e6-8e12-a2e2770fa21b.png)

**Comment by MayeulChassagnard** [comment]
@thewtex @jcfr Let me know if you have an idea of where it may comes from.

I was suspecting that it could comes from the slicer-build-base..

**Comment by thewtex** [comment]
@MayeulChassagnard This likely comes from a build error in *slicer-build-deps*

**Comment by MayeulChassagnard** [comment]
I'm trying to rebuild (`bash build.sh` in `slicer/slicer-build-base`) but if this issue isn't solved after that, I really don't know what I am supposed to do to fix it...

The thing is that if `slicer/slicer-build` contains at every time the build and also the tests, the job is done for the Continuous Integration of Slicer

**Comment by MayeulChassagnard** [comment]
Looks like that rebuilding `slicer/slicer-build-base` doesn't produce anymore this error!
_Build in progress: Hope we won't have any other errors_

**Comment by thewtex** [comment]
:+1:  :-)

**Comment by MayeulChassagnard** [comment]
Work well!
